app = "infamous-freight-api"
primary_region = "dfw"

[build]
dockerfile = "Dockerfile"

[deploy]
strategy = "rolling"
wait_timeout = "10m0s"

[env]
HOST = "0.0.0.0"
NODE_ENV = "production"
PORT = "4000"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 4_000
min_machines_running = 1
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "1m30s"
  interval = "30s"
  method = "GET"
  path = "/api/health"
  timeout = "15s"

  [http_service.concurrency]
  hard_limit = 40
  soft_limit = 25
  type = "requests"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
